export interface LegalSection {
  heading: string;
  body: string;
}

// Placeholder contact — swap in a real address before this goes live.
export const LEGAL_CONTACT_EMAIL = "privacy@ag-ai.example";

export const PRIVACY_POLICY_SECTIONS: LegalSection[] = [
  {
    heading: "What this app stores",
    body:
      "AG-AI stores your chat messages in your browser's localStorage so your conversation " +
      "persists across page reloads. This data stays on your device and is not sold or shared " +
      "with third parties.",
  },
  {
    heading: "What the server sees",
    body:
      "When a backend is configured, each message you send is forwarded to a self-hosted " +
      "language model for processing and is durably saved server-side (MongoDB) so the " +
      "conversation can be recalled or searched later. No analytics or advertising cookies are " +
      "set by this app today.",
  },
  {
    heading: "Third parties",
    body:
      "This app does not use third-party analytics, advertising, or tracking scripts at this " +
      "time. If that changes, this policy and the cookie consent banner will be updated first.",
  },
  {
    heading: "Your choices",
    body:
      "You can clear your local chat history at any time by clearing your browser's site data " +
      "for this page. To request deletion of server-side data, contact us at the address below.",
  },
  {
    heading: "Contact",
    body: `Questions about this policy can be sent to ${LEGAL_CONTACT_EMAIL}.`,
  },
];

export const TERMS_SECTIONS: LegalSection[] = [
  {
    heading: "Using this app",
    body:
      "AG-AI is a demo chatbot project. It is provided as-is, without warranty of any kind, and " +
      "may be unavailable or change at any time without notice.",
  },
  {
    heading: "AI-generated content",
    body:
      "Replies are generated by a language model and may be inaccurate, incomplete, or " +
      "inappropriate. Do not rely on them for medical, legal, financial, or safety-critical " +
      "decisions.",
  },
  {
    heading: "Acceptable use",
    body:
      "Don't use this app to send unlawful, abusive, or harmful content, or attempt to disrupt, " +
      "overload, or gain unauthorized access to the underlying service.",
  },
  {
    heading: "Changes",
    body: "These terms may be updated as the project evolves; continued use means you accept the current version.",
  },
  {
    heading: "Contact",
    body: `Questions about these terms can be sent to ${LEGAL_CONTACT_EMAIL}.`,
  },
];
